version: '2.3'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - bd-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "3307:8080"
    networks:
      - bd-network

networks:
  bd-network:
    driver: bridge
