version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: tsauth
    networks: 
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080
    networks: 
      - postgres
networks: 
  postgres:
    driver: bridge