version: "3.7"

services:
  redis:
    image: redis:alpine
    # init: true
    deploy:
      restart_policy:
        condition: on-failure # Condição de restart  possiveis: none | on-failure | any (default)
        delay: 5s # Quanto tempo esperar entre as tentativas de restart
        max_attempts: 3 # Quantidade de vezes para tentar reiniciar antes de desistir | default = nunca
        window: 20s # Tempo para determinar se uma reinicialização foi bem sucedida
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   # test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
    #   # test: curl -f https://localhost || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    logging:
      driver: "json-file" # json-file | syslog | none
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  db-data:
networks:
  overlay: